name: Deploy Cloud Function
on:
  push:
    branches: [ dev ]
    paths:
        - main.py
        - .github/workflows/pipeline.yml
env:
  PROJECT: latam_challenge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.PROJECT}}
          service_account_key: ${{secrets.GOOGLE_CREDENTIALS}}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: latam__challenge
          runtime: python39
          project_id: ${{env.PROJECT}}
          entry_point: main

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding latam__challenge --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"

